### ISSUE TITLE
Recenze na GPT Czech Poet

### ISSUE THREAD

**Issue by ptakopysk** [ufal/edupo#1]
Přečíst článek [GPT Czech Poet: Generation of Czech Poetic Strophes with Language Models](https://openreview.net/forum?id=QtsxVTg8ux) a napsat na něj podrobnou strukturovanou recenzi:
- posouzení celkové myšlenky
- kritické zhodnocení evaluace
- kritické zhodnocení metody
- návrhy na vylepšení metody a evaluce
- návrhy na rozšíření metody a evaluce
- rešerše dalších souvisejících prací

**Comment by tomasmcz** [comment]
@ptakopysk OpenReview říká, že ten článek nemám právo zobrazit.

Jakou relevanci vidíš v těch byte LM? A nebyl ten Jindřichův článek o char modelech (a ještě možná pro překlad?)?

**Comment by ptakopysk** [comment]
Zajímavé. Zkouším přiložit PDF:
[1490_gpt_czech_poet_generation_of_c.pdf](https://github.com/ufal/edupo/files/14028732/1490_gpt_czech_poet_generation_of_c.pdf)

**Comment by ptakopysk** [comment]
> Jakou relevanci vidíš v těch byte LM? A nebyl ten Jindřichův článek o char modelech (a ještě možná pro překlad?)?

V Byte LM vidím relevanci v tom, že když @jinymusim použil Byte LM, tak mu v několika kritériích vyšly nejlepší výsledky. Respektive nevím, jestli se nějak liší Byte LM a ta použitá Unicode tokenizace, ale myšlenkově je to každopádně podobné, tokenizace na fakt malé jednotky, character nebo byte. (Nevim o čem byl Jidnřichův článek, nečet jsem ho.)

**Comment by tomasmcz** [comment]
Hotovo, recenzi jsem předal ústně a papírově.
